local state = require("opencode.state")
local sync = require("opencode.sync")
local forms = require("opencode.question.state")
local permissions = require("opencode.permission.state")
local pending = require("opencode.session.pending")
local client = require("opencode.client")
local bus = require("opencode.events.bus")
local function form(id, sid)
	return { id = id, sessionID = sid or "root", title = "Continue?", fields = { { key = "ok", type = "boolean", required = true } } }
end

describe("v2 interaction recovery", function()
	local saved, requests
	before_each(function()
		state.reset(); sync.clear_all(); forms.clear_all(); permissions.clear_all(); pending.clear_all(); bus.clear()
		state.upsert_session({ id = "root", directory = "/tmp/project" })
		state.set_session("root", "Root")
		saved, requests = {}, { permissions = {}, forms = {}, detail = {} }
		for _, method in ipairs({ "list_permissions", "list_questions", "get_form", "get_permission" }) do saved[method] = client[method] end
		client.list_permissions = function(opts, cb) requests.permissions[opts.session_id] = cb end
		client.list_questions = function(opts, cb) requests.forms[opts.session_id] = cb end
		client.get_form = function(sid, id, cb) requests.detail[id] = cb end
		client.get_permission = function(sid, id, cb) requests.detail[id] = cb end
		require("opencode.events.handlers.interactions_v2").setup(bus)
	end)
	after_each(function()
		for method, original in pairs(saved) do client[method] = original end
		bus.clear(); forms.clear_all(); permissions.clear_all(); state.reset(); pending.clear_all()
	end)
	local function event(kind, data)
		bus.emit("v2_interaction", { id = "evt", type = kind, created = 1000, data = data })
	end
	it("keeps a cancelled form out of an older pending list", function()
		bus.emit("connected")
		event("form.cancelled", { id = "f", sessionID = "root" })
		requests.forms.root(nil, { form("f") })
		assert.is_nil(forms.get_question("f"))
	end)
	it("preserves keyed draft and submitting state during repeated snapshots", function()
		event("form.created", { form = form("f") })
		forms.select_option("f", 2)
		forms.begin_submission("f")
		bus.emit("connected")
		requests.forms.root(nil, { form("f") })
		assert.is_true(forms.get_question("f").submitting)
		assert.same({ ok = false }, forms.get_answers("f"))
		requests.detail.f(nil, vim.tbl_extend("force", form("f"), { state = { status = "answered", answer = { ok = true } } }))
		assert.same({ ok = true }, forms.get_question("f").answers)
	end)
	it("invalidates callbacks across disconnect, cleanup and closing sessions", function()
		bus.emit("connected")
		bus.emit("disconnected")
		requests.forms.root(nil, { form("f") })
		assert.is_nil(forms.get_question("f"))
		bus.emit("connected")
		forms.clear_all()
		requests.forms.root(nil, { form("f") })
		assert.is_nil(forms.get_question("f"))
		bus.emit("connected")
		pending.clear_session("root")
		requests.forms.root(nil, { form("f") })
		assert.is_nil(forms.get_question("f"))
	end)
	it("keeps native edit permissions separate from diff review and terminal replies monotonic", function()
		local data = { id = "p", sessionID = "root", action = "neovim_edit", resources = { "x.lua" }, save = { "*.lua" },
			source = { type = "tool", messageID = "msg", id = "call" }, metadata = { diff = "untrusted arbitrary diff" } }
		event("permission.asked", data)
		local item = permissions.get_permission("p")
		assert.equals("permission", item.transport)
		assert.equals("call", item.call_id)
		assert.same({ "*.lua" }, item.always)
		assert.is_nil(require("opencode.edit.state").get_edit("p"))
		bus.emit("connected")
		event("permission.replied", { requestID = "p", sessionID = "root", reply = "reject" })
		requests.permissions.root(nil, { data })
		assert.equals("rejected", item.status)
		assert.is_false(permissions.mark_approved("p", "once"))
	end)
	it("recovers disappeared permission as unavailable without inventing an approval", function()
		event("permission.asked", { id = "p", sessionID = "root", action = "read", resources = {} })
		bus.emit("connected")
		requests.permissions.root(nil, {})
		requests.detail.p({ status = 404 })
		assert.equals("unavailable", permissions.get_permission("p").status)
		assert.is_nil(permissions.get_permission("p").reply)
	end)
end)
