local state = require("opencode.state")
local logger = require("opencode.logger")
local viewer = require("opencode.ui.log_viewer")

describe("retained log entries", function()
	local config
	before_each(function()
		config = state.get_config()
		logger.clear()
	end)
	after_each(function()
		viewer.close()
		logger.clear()
		state.set_config(config)
	end)

	it("retains only the newest entries up to the configured limit", function()
		state.set_config({ logs = { max_entries = 2 } })
		logger.debug("first")
		logger.debug("second")
		logger.debug("third")
		assert.same({ "second", "third" }, vim.tbl_map(function(entry) return entry.message end, logger.get_logs()))
	end)

	it("renders distinct entries even when they concern the same message", function()
		logger.debug("old update", { data = { part = { messageID = "msg_log_rebuild" } } })
		logger.debug("new update", { data = { part = { messageID = "msg_log_rebuild" } } })
		viewer.open({ position = "bottom", height = 8 })
		local bufnr = vim.api.nvim_get_current_buf()
		assert.equals("opencode_logs", vim.bo[bufnr].filetype)
		local text = table.concat(vim.api.nvim_buf_get_lines(bufnr, 0, -1, false), "\n")
		assert.is_truthy(text:find("old update", 1, true))
		assert.is_truthy(text:find("new update", 1, true))
	end)
end)
