local edits = require("opencode.edit.state")
local changes = require("opencode.artifact.changes")
describe("v2 edit review safety", function()
	local path, old_notify
	before_each(function()
		require("opencode.state").set_connection("connected")
		require("opencode.state").set_config({ server = { shared_filesystem = true } })
		path = vim.fn.tempname(); old_notify = vim.notify; vim.notify = function() end
		edits.clear_all(); changes.clear()
	end)
	after_each(function() vim.notify = old_notify; vim.fn.delete(path); edits.clear_all(); changes.clear(); require("opencode.state").set_connection("idle") end)
	local function write(bytes) local f = assert(io.open(path, "wb")); f:write(bytes); f:close() end
	local function read() local f = assert(io.open(path, "rb")); local bytes = f:read("*a"); f:close(); return bytes end
	local function add()
		write("before\n")
		return edits.add_edit("r", "s", { { fileID = "f", filePath = path, before = "before\n", after = "after\n", type = "update" } },
			{ transport = "review_rpc", revision = 1, native_review = { status = "pending" } })
	end
	it("does not apply or flush review files while disconnected", function()
		add(); require("opencode.state").set_connection("idle")
		assert.is_false(edits.accept_file("r", 1))
		assert.is_false(edits.resolve_all("r"))
		assert.equals("before\n", read())
	end)
	it("external review defers accepted writes and blocks local manual/diff paths", function()
		require("opencode.state").set_config({ server = {} })
		require("opencode.state").set_server_managed(false)
		local item = add()
		assert.equals("server", item.apply_mode)
		assert.is_nil(item.files[1].change_id)
		assert.is_true(edits.accept_file("r", 1))
		assert.equals("before\n", read())
		assert.is_false(edits.resolve_file("r", 1))
		local count = #vim.api.nvim_list_wins()
		require("opencode.ui.native_diff").show(nil, item.files, { edit_id = "r" })
		require("opencode.ui.chat.edits").open_inline_diff_split(item.files[1], { edit_id = "r" })
		assert.equals(count, #vim.api.nvim_list_wins())
	end)
	it("preserves a changed BOM or EOL before client apply", function()
		for _, bytes in ipairs({ "before\r\n", "\239\187\191before\n" }) do
			add(); write(bytes)
			assert.is_true(edits.accept_file("r", 1))
			assert.equals(bytes, read())
		end
	end)
	it("does not permit stale local actions after cancellation or revive pending snapshots", function()
		local item = add()
		assert.is_true(edits.set_review_record({ reviewID = "r", sessionID = "s", revision = 1, status = "cancelled" }))
		assert.is_false(edits.accept_file("r", 1))
		assert.is_false(edits.resolve_file("r", 1))
		assert.is_false(edits.accept_all("r"))
		assert.is_false(edits.set_review_record({ reviewID = "r", sessionID = "s", revision = 1, status = "pending" }))
		assert.equals("cancelled", item.native_review.status)
		assert.equals("before\n", read())
	end)
	it("keeps settled metadata when admission arrives after the terminal event", function()
		local item = add()
		assert.is_true(edits.set_review_record({ reviewID = "r", sessionID = "s", revision = 1, status = "settled", outcome = { wrote = false } }))
		assert.is_false(edits.set_review_record({ reviewID = "r", sessionID = "s", revision = 1, status = "decided" }))
		assert.equals("settled", item.native_review.status)
		assert.is_false(item.metadata.wrote)
	end)
end)
