describe("v2 session selection ownership", function()
	local state, sync = require("opencode.state"), require("opencode.sync")
	local choices, pending = require("opencode.session.selection"), require("opencode.session.pending")
	local local_state, selectors = require("opencode.local"), require("opencode.selectors")
	before_each(function()
		state.reset(); sync.clear_all(); choices.clear_all(); pending.clear_all()
		sync.handle_agents({ { id = "build", name = "Builder" }, { id = "plan", name = "Planner" } })
		sync.handle_providers({ { id = "p", models = { one = { variants = { fast = {} } }, two = { variants = {} } } } })
		state.upsert_session({ id = "a", agent = "build", model = { providerID = "p", id = "one", variant = "fast" } })
		state.upsert_session({ id = "b", agent = "plan", model = { providerID = "p", id = "two" } })
		state.set_session("a", "A")
	end)
	after_each(function() choices.clear_all(); pending.clear_all(); sync.clear_all(); state.reset() end)
	it("retains native selection across tab switches and routes choices to the addressed session", function()
		assert.equals("one", local_state.model.current().modelID)
		assert.equals("build", local_state.agent.current().id)
		local other = selectors.send_selection({ session_id = "b" })
		assert.equals("two", other.model.modelID); assert.equals("plan", other.agent); assert.is_nil(other.variant)
		local_state.model.set({ providerID = "p", modelID = "two" })
		assert.equals("two", selectors.send_selection().model.modelID)
		assert.is_nil(selectors.send_selection().variant)
		state.set_session("b", "B")
		assert.equals("plan", local_state.agent.current().id)
		state.set_session("a", "A")
		assert.equals("two", selectors.send_selection().model.modelID)
		pending.clear_session("a")
		assert.equals("one", selectors.send_selection().model.modelID)
	end)
	it("clears an explicitly reset variant without borrowing another session's choice", function()
		assert.equals("fast", local_state.variant.current())
		local_state.variant.set(nil)
		assert.is_nil(selectors.send_selection().variant)
		assert.is_nil(selectors.send_selection().model.variant)
		state.set_session("b", "B")
		assert.is_nil(selectors.send_selection().variant)
	end)
	it("does not carry an unsent variant choice into a different model", function()
		local_state.variant.set("fast")
		local_state.model.set({ providerID = "p", modelID = "two" })
		assert.is_nil(selectors.send_selection().variant)
		assert.is_nil(local_state.variant.current())
	end)
	it("treats native default as the absence of a variant and explicit model changes clear the old variant", function()
		local request = require("opencode.protocol.v2.requests")
		assert.same({ providerID = "p", id = "one" }, request.model({ providerID = "p", id = "one", variant = "default" }))
		local chosen = selectors.send_selection({ model = { providerID = "p", id = "two" } })
		assert.is_nil(chosen.variant)
	end)
end)
